version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    depends_on:
      - db
    # environment:
    #   - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
  db: 
    build: db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data